export interface Point {
    questionId: string,
    Maxpoint: number,
    AvaragePoint: number,
    Budapest: number | undefined,
    KozepDunantul: number | undefined,
    PestMegye: number | undefined,
    NyugatDunantul: number | undefined,
    EszakMagyarorszag: number | undefined,
    DelAlfold: number | undefined,
    EszakAlfold: number | undefined,
    DelDunantul: number | undefined,
    Szallashely: number | undefined,
    Epitoipar: number | undefined,
    Penzugy: number | undefined,
    Adminisztrativ: number | undefined,
    Kereskedelem: number | undefined,
    Ingatlan: number | undefined,
    Feldolgozoipar: number | undefined,
    Informacio: number | undefined,
    Egyeb: number | undefined,
    Szakmai: number | undefined,
    Villamosenergia: number | undefined,
    Szallitas: number | undefined,
    Mezogazdasag: number | undefined,
    otkilenc: number | undefined,
    husznegyvenkilenc: number | undefined,
    tiztizenkilenc: number | undefined,
    otvenketszaznegyvenkilenc: number | undefined,
    ShownPoint: number
  }